openapi: 3.0.3
info:
    title: TODO API
    version: 1.0.0
    description: >
        API de gestion d'une TODO List.
servers:
    - url: http://localhost:8080
      description: Serveur local de dÃ©veloppement

tags:
    - name: tasks
      description: OpÃ©rations sur les tÃ¢ches

paths:
    /tasks:
        post:
            tags: [ tasks ]
            summary: CrÃ©er une tÃ¢che
            operationId: createTask
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            $ref: '#/components/schemas/Task'
            responses:
                '201':
                    description: TÃ¢che crÃ©Ã©e avec succÃ¨s
                    headers:
                        Location:
                            description: URL de la ressource crÃ©Ã©e
                            schema:
                                type: string
                                example: /tasks/1
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/Task'
        get:
            tags: [ tasks ]
            summary: RÃ©cupÃ©rer toutes les tÃ¢ches
            description: RÃ©cupÃ©rer toutes les tÃ¢ches
            responses:
                '200':
                    description: TÃ¢ches trouvÃ©es avec succÃ¨s
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/Tasks'
                '404':
                    description: TÃ¢che non trouvÃ©e




        delete:
            tags: [ tasks ]
            summary: Supprime toutes les tÃ¢ches
            description: Supprime tputes tÃ¢ches
            responses:
                '204':
                    description: TÃ¢che supprimÃ©e avec succÃ¨s

                '404':
                    description: TÃ¢che non trouvÃ©e


    /tasks/{id}:
        parameters:
            - in: path
              name: id
              required: true
              description: Identifiant numÃ©rique de la tÃ¢che
              schema:
                  type: integer
                  minimum: 1
        get:
            tags: [ tasks ]
            summary: RÃ©cupÃ©rer une tÃ¢che
            description: RÃ©cupÃ©rer une tÃ¢che par son identifiant
            operationId: getTaskById
            responses:
                '200':
                    description: TÃ¢che trouvÃ©e avec succÃ¨s
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/Task'
                '404':
                    description: TÃ¢che non trouvÃ©e


        delete:
            tags: [ tasks ]
            summary: Supprime une tÃ¢che
            description: Supprime une tÃ¢che par son identifiant
            operationId: deleteTaskById
            responses:
                '204':
                    description: TÃ¢che supprimÃ©e avec succÃ¨s

                '404':
                    description: TÃ¢che non trouvÃ©e


        put:
            tags: [ tasks ]
            summary: modifie une tÃ¢che
            description: modifie une tÃ¢che par son identifiant
            operationId: putTaskById
            responses:
                '204':
                    description: TÃ¢che modifiÃ©e avec succÃ¨s

                '404':
                    description: TÃ¢che non trouvÃ©e
    /tasks/count:
        get:
            tags: [ tasks ]
            summary: Nombre de tÃ¢che
            description: renvoie le nombre de tÃ¢ches
            responses:
                '200':
                    description: Nombre de tÃ¢che comptÃ©e avec succÃ¨s
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/Task'

                '404':
                    description: TÃ¢che non trouvÃ©e





components:
    schemas:
        Task:
            type: object
            description: ReprÃ©sentation d'une tÃ¢che
            properties:
                id:
                    type: integer
                    example: 1
                title:
                    type: string
                    nullable: false
                    example: Acheter du lait
                description:
                    type: string
                    nullable: true
                    example: 2L demi-Ã©crÃ©mÃ©
                done:
                    type: boolean
                    nullable: false
                    example: false
            required:
                - id
                - title
                -

        Task2:
            type: object
            description: ReprÃ©sentation d'une autre tÃ¢che
            properties:
                id:
                    type: integer
                    example: 2
                title:
                    type: string
                    nullable: false
                    example: Acheter de cÃ©rÃ©ales
                description:
                    type: string
                    nullable: true
                    example: chocapic
                done:
                    type: boolean
                    nullable: false
                    example: false
            required:
                - id
                - title

        Tasks:
            type: array
            items:
                oneOf:
                    - $ref: "#/components/schemas/Task"
                    - $ref: "#/components/schemas/Task2"



